### ISSUE TITLE
Chapter 1 - Technical Feedback

### ISSUE THREAD

**Issue by natec425** [ASoledadU/head-first-java-cliffsnotes-example#1]
Peer Reviewers: @devinbooker616, @DerekStegall

---

https://github.com/ASoledadU/head-first-java-cliffsnotes-example/blob/51bcc43a43e1e97e3cc66d5e53245e9be39a6529/chapter-1-breaking-the-surface/README.md#L21-L26

You said "Class File," but it should be "Class". The source file contains a single class, that contains many methods, that contains many statements.

- [ ] @devinbooker616
- [ ] @DerekStegall

---

https://github.com/ASoledadU/head-first-java-cliffsnotes-example/blob/51bcc43a43e1e97e3cc66d5e53245e9be39a6529/chapter-1-breaking-the-surface/README.md#L38

A class can have zero methods.

- [ ] @devinbooker616
- [ ] @DerekStegall

**Comment by ASoledadU** [comment]
These issues have been taken care of on the latest push.
